### ISSUE TITLE
Visual glitch when CR hijack is on

### ISSUE THREAD

**Issue by N-R-K** [gosukiwi/vim-smartpairs#1]
When `g:smartpairs_hijack_return` is turned on, pressing enter I can see vim going in and out of insert mode for a split second which is very jarring.

For reference I've been using [auto-pairs](https://github.com/jiangmiao/auto-pairs) thus far and it doesn't have this issue (but it has other issues, and so I was looking for something simpler).

- - -

Also, the documentation is currently not correct. It references `g:smartpairs_hijack_enter` which doesn't exist (it should be `_return` not `_enter`).

**Comment by gosukiwi** [comment]
Thanks for the issue! I updated the documentation, as for the flickering, it's because it does `<C-O>O` to "open up" a new line with proper indentation. I can't think of another easy way to do that, considering the indentation is optional, for example, if you do `(<CR>` inside a JavaScript file, it will do this:

```
(
  _cursor here, with default indentation for this file (eg: 2 spaces)
)
```

But with a txt file, it will do this:

```
(
_cursor here, with no indentation, as txt format doesn't have any indentation here
)
```

I wonder if there's a way from insert mode to do just that besides `<C-O>O`.

To me though it seems to not flicker, maybe it's because of `lazyredraw`?

**Comment by N-R-K** [comment]
A couple more info:

1. The issue doesn't always happen, it's more closer to 2/10 times (and seems to happen most consistently when the cursor is that the bottom of the screen. perhaps something to do with how ncurses draws)
2. I have nolazyredraw set apparently. Using `:set lazyredraw` seems to make it much rarer, but it's still noticeable about 1/25 times.
3. `auto-pairs` also goes in and out of insert mode (I checked out it's source a couple hours after opening the issue). It does something like `<ESC>k==o`. Perhaps I just got lucky with auto-pairs somehow and avoided most of the noticeable cases (and I've uninstalled auto-pairs, so can't/don't want to test it anymore).
4. I also tried to see if it can be done from insert mode but didn't find anything.
5. I have `listchars` set to make leading spaces visible as `.` in normal mode, which is why when it goes in and out of insert the visual is a bit more noticeable for me.

But in any case, I'm pretty happy with the plugin so far and it's a minor issue in comparison. So if it's something that's inherently not fixable then that's not a big deal. But would be nice if it can be fixed, of course :)

**Comment by gosukiwi** [comment]
I'll keep an eye on this and see if I can come up with a nice way to avoid going into normal mode and then back into insert mode for that, glad you found this plugin useful :)

Cheers!

**Comment by N-R-K** [comment]
I've been using this for the past 2 days:

```diff
   if has_key(b:smartpairs_pairs, prevchar) && nextchar == b:smartpairs_pairs[prevchar]
-    return "\<CR>\<C-O>O"
+    return "\<CR>\<UP>\<END>\<CR>"
   else
     return "\<CR>"
   endif
```

This works due to `cinwords`, so `smartindent` or `cindent` needs to be enabled for this to work.

For my use-cases, it's been working really well. But I have only tested a few amount of filetypes. So cannot say how well it'd work across a wide variety of filetypes.

**Comment by gosukiwi** [comment]
Thanks, I'll give it a shot when I have some time, in theory I think that should work as well as `<C-O>O`

**Comment by gosukiwi** [comment]
Seems to be working for me, so I just merged it for now 🚢
