### ISSUE TITLE
In a Go file ( is not working

### ISSUE THREAD

**Issue by lucasgrvarela** [gosukiwi/vim-smartpairs#3]
All the other pairs are being auto completed with the exception of ( no matter where I put it, empty line or after text, it nevers auto complete it.

I'm using the default configuration for your plugin.

It's being detect in some way because when I insert manually (_) and press `<CR>` with the cursor inside the pairs it adds the right indentation.

```
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct  6 2023 19:27:28)
```

my vimrc
```
filetype plugin indent on
syntax on

set autoindent 
set background=light
set backspace=indent,eol,start 
set clipboard=unnamedplus 
set expandtab 
set foldopen-=search 
set guicursor=
set hidden 
set ignorecase 
set incsearch 
set laststatus=2
set mouse=a
set nobackup 
set noswapfile
set nowrap 
set number 
set relativenumber
set scrolloff=999
set shiftwidth=4 
set shortmess-=S 
set showcmd 
set smartcase
set softtabstop=4 
set statusline=%<%F\ %h%m%r%{FugitiveStatusline()}%=%-14.(%l,%c%V%)\ %P
set tabstop=4 
set termguicolors 
set ttimeout
set ttimeoutlen=100
set wildmenu 

let mapleader = " "
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
inoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<TAB>"
inoremap <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
nnoremap <C-p> "0p
nnoremap <leader><space> :Buffers<CR> 
nnoremap <leader>c :cd %<CR>
nnoremap <leader>e :E<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>g :RG<CR>
nnoremap <leader>n :cn<CR>
nnoremap <leader>p :cp<CR>
nnoremap <leader>s :G<CR>
nnoremap <leader>y :let @+=expand("%") . ':' . line(".")<CR>
nnoremap K :LspHover<CR>
nnoremap gd :LspGotoDefinition<CR>
nnoremap gr :LspShowReferences<CR>

if empty(glob('~/.vim/autoload/plug.vim'))
    silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim.plugged')
Plug 'gosukiwi/vim-smartpairs'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'morhetz/gruvbox'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'yegappan/lsp'
call plug#end()

let g:netrw_list_hide='\(^\|\s\s\)\zs\.\S\+'
let g:netrw_banner=0
let g:gruvbox_contrast_light="medium"
let $BAT_THEME = 'gruvbox-light'
colorscheme gruvbox

autocmd VimEnter * call LspAddServer([#{ name: 'golang', filetype: ['go', 'gomod'], path: 'gopls', args: ['serve'], syncInit: v:true }, 
            \ #{ name: 'solargraph', filetype: ['ruby'], path: 'solargraph', args: ['stdio'], syncInit: v:true },
            \ #{ name: 'terraform-ls', filetype: ['terraform'], path: 'terraform-ls', args: ['serve'], syncInit: v:true }])
autocmd VimEnter * call LspOptionsSet(#{noNewlineInCompletion: v:true})
autocmd BufWritePre *.go,*.rb,*.tf call execute('LspFormat')
```

**Comment by gosukiwi** [comment]
Hi @lucasgrvarela, that's interesting. Do other pairings work?

When I try it myself in a Go file it seems to work. Maybe try uncommenting plugins/mappings one by one to see if that fixes it?

What happens if you go to a Go file and type `:imap`? You should see something like:

![image](https://github.com/gosukiwi/vim-smartpairs/assets/161972/d6fd5f76-8f9d-40af-afed-7af059742c34)

You can also try other filetypes and see if you are missing pairs.

**Comment by lucasgrvarela** [comment]
Looks like the conflict is happening with yegappan/lsp and showSignature code.

![image](https://github.com/gosukiwi/vim-smartpairs/assets/37870368/5b53a0ba-444f-499a-851a-72d33d2dda4a)

After defining showSignature option to not be enabled your plugin started to working fine because the map is not being override anymore.
```
autocmd VimEnter * call LspOptionsSet(#{noNewlineInCompletion: v:true, showSignature: v:false})
```

![image](https://github.com/gosukiwi/vim-smartpairs/assets/37870368/f780635e-2f29-4493-99e2-864d229aae11)

Any idea how to have both features enabled (your plugin + showSignature: v:true) or it will not be possible?

**Comment by gosukiwi** [comment]
Mmm I see. I think there might be a way to call the original mapping, but I'd need to investigate this in depth. I don't have the time to do it now but you are welcome to take a look if you want :P

Alternatively, I guess you could try and remap the bindings defined in `yegappan/lsp`, there might be options for you to use. Another alternative would be `vim-lsp`. I use it together with `vim-lsp-settings` and it works nicely for me.

**Comment by gosukiwi** [comment]
Taking a quick look, @lucasgrvarela what if you try replacing the `s:SetUpMappings` function with the snippet below?

```vimscript
function! s:SetUpMappings() abort
  let keys = keys(b:smartpairs_pairs)
  for opening in keys
    execute 'imap <script><expr><buffer><silent> ' . opening . ' <SID>InsertOrJump("' . escape(opening, '"') . '", "' . escape(b:smartpairs_pairs[opening], '"') . '")'
    if opening != b:smartpairs_pairs[opening]
      execute 'imap <script><expr><buffer><silent> ' . b:smartpairs_pairs[opening] . ' <SID>Jump("' . escape(b:smartpairs_pairs[opening], '"') . '")'
    endif
  endfor
endfunction
```

Basically that will make the mappings recursive (using `imap` instead of `inoremap`), and maybe they will pick up your other plugin's config.

Other than that, looks like the lsp plugin has priority so its mapping are being picked up instead of smartpairs mappings.

**Comment by lucasgrvarela** [comment]
Unfortunately didn't work. I won't have time to test new stuffs so you don't need to bother on this issue unless you want to try to solve for further cases or to check how other plugin authors are handling this conflict situation. I decided to not use auto complete pairs for now. I'm still in learning phase of vim, so a minimal setup is what I will be using for now, till i Grok vi, in any case thank you for your help, if you want to close or keep it open it's up to you.
